seatgeek/druzhba

druzhba/main.py, druzhba/table.py
The `InvalidSchemaError` raised when PKs are found missing was lacking the template parameters expected by the logging in `main`. This removes the expectation that these exceptions take two template parameters, which I think is a weird and brittle pattern.
=> Don't require a specific string template pattern for schema errors

druzhba/table.py, test/integration/config/mysqltest.yaml, test/integration/test_mysql_to_redshift.py
Fixes a bug where providing `index_sql` in a yaml template would cause an infinite loop, since `run_template_data` references `new_index_value`.
=> Revert run_template_data to index query. Add integration test

setup.py
The newest version of PyMysql no longer exposes these custom datetime type conversions we use to implement the `not_null_date` configuration feature.
=> Disallow newest pymysql version

docs/configuration.rst, druzhba/db.py, druzhba/main.py, druzhba/postgres.py, druzhba/table.py, test/integration/test_postgres_to_redshift.py, test/unit/test_db.py, test/unit/test_postgres.py
* Allows for additional parameters to the `connection_string` (e.g. `sslmode`). These are collected from the query string in the connection url
* Fixes an issue when the username or password in the connection string has characters that need to be url-encoded (for example, if a password has `?` in it)
* Enable environment variable parsing on the database YAML
* Update the Postgres queries for table indices and columns to be compatible with Redshift
* Added tests
* Updated docs
I think there are some files that `black` will reformat, but I left alone the ones I didn't touch.
Unit test and integration tests run.
I tested using a Redshift source (via the Postgres source type) and was able to confirm a successful run.
=> Add options for connecting to Postgres

druzhba/table.py, test/unit/test_table.py
Previously, if `query_file` was set for a table, a full refresh would not work because the `run.old_index_value` would still have a value and the custom SQL would respect that.
Now, `old_index_value` always returns `None` if full refreshing, which enables full refreshes if there is a `query_file`.
There are some files that black will reformat, but I left alone the ones I didn't touch.
Unit test and integration tests run.
=> Set old_index_value to None for full refresh

docs/conf.py, docs/configuration.rst, druzhba/main.py, test/init_psql/initdb_citext.sh, test/integration/config/_pipeline.yaml, test/integration/config/pgtest_data.yaml, test/unit/test_main.py
For increased flexibility, we would like to be able to define a source database config YAML separately from the database alias in `_pipeline.yaml`. This is particularly useful when we have the same source database config we want to apply against multiple databases.
Now:
* `config_name` in `_pipeline.yaml` allows a different location of the source database config YAML besides `alias`
* `config` in `_pipeline.yaml` allows `connection_string`, `connection_string_env`, and `data` to override what is in the source database config YAML
Unit test and integration tests run.
=> Allow database config variables to be defined in pipeline config

druzhba/postgres.py
https://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html#r_Numeric_types201-decimal-or-numeric-type
=> Redshift supports a maximum precision and scale that is less then Postgres

druzhba/table.py
This change is particularly related to some instances we've seen
where there's a huge time delta (on the scale of hours) between
loading the old index value and starting the extract query (or at
least between the timestamps of the relevant "Index found" and
"Extracting" logs) but we can't exactly place where the query to
load the new index value falls on that timeline.
=> Log the new index value when it is first loaded

druzhba/mssql.py, druzhba/mysql.py, druzhba/postgres.py, druzhba/table.py, test/unit/test_table.py
This method is currently called twice, each time executing a query
against the source database. The cache should cut the down to once
and hopefully save significant unnecessary work in some cases.
=> Cache the result of get_sql_description on TableConfig

druzhba/mssql.py, druzhba/mysql.py, druzhba/postgres.py, druzhba/table.py, test/unit/test_table.py
Reverts seatgeek/druzhba#62
Deploying this commit we encountered an issue with the index table being updated without the actual data loaded in Redshift. Reverting the commit out allowed things to proceed as intended. The details still need to be investigated; I will follow up here with the details once identified.
=> Revert "Cache the result of get_sql_description on TableConfig"

druzhba/postgres.py
The original precision/scale gets also appended (e.g. numeric(18,2) with a type_map['numeric'] = 'numeric(19,2)' ends up as numeric(18,2)(19,2). This will fix the bug.
=> Support numeric type with precision

druzhba/postgres.py
Previously we had the following behaviour: 
numeric(18,2) with a type_map['numeric'] = 'numeric(19,2)' ends up as numeric(18,2)(19,2) 
this PR will fix that issue.
=> fixed type map overriding of numeric types

docs/configuration.rst, druzhba/postgres.py
This PR allows columns to specify their type, without having to change other similar types. It works like the following example:
```
type_map:
numeric(19,2): numeric(10,2) // standard type map declaration
columns:
exchange_rate: numeric(12,2) // per column type map declaration
```
=> per-column type map support added

druzhba/table.py
we will not be changing this to decimal, since string works in all the cases we have seen. Updating comment to remove confusion.
=> updating string/decimal comment

druzhba/table.py
The new_index_value is captured lazily when the property is first
accessed. Unfortunately, for the full_refresh case this currently
doesn't happen until after the extraction completes which means
that the resulting index may potentially get ahead of the data,
which is bad. This change makes sure that full_refresh uses the
new_index_value within the query WHERE clause.
=> Make sure that new_index_value is captured before full_refresh

druzhba/table.py
This is useful for debugging in cases where Druzhba fails later on
in the process (e.g. during the extract query). The CREATE TABLE
statement is already computed and validated prior to running the
extract so there's really no reason not to log it then also.
=> Log the CREATE TABLE statement at the time it is first determined

druzhba/main.py
The documentation and implementation both name the argument
db_alias but a few instances of calling code pass the argument
as database, leading to incomplete metrics. This change fixes that
inconsistency and calls it db_alias everywhere.
=> Fix kwargs passed to MonitoringProvider.on_event

druzhba/avro.py
This protects us from rows  with a ridiculously large column.
=> Truncate varchar columns to the maxmimum varchar size

druzhba/avro.py
Fixes a failing conversion from Python byte-string when the Avro field-type is [null, string]
=> Convert Python byte-string to string for Avro

test/unit/test_table.py
this test was breaking the build, removing it as it's redundant anyway
=> rm unused test

druzhba/mssql.py, druzhba/mysql.py, druzhba/postgres.py, druzhba/table.py
tweak to give index_sql awareness of old_index_value so that we have more control over the new_index_value
=> Add `old_index_value` to `index_sql` 

druzhba/table.py, test/unit/test_table.py
Add a config param to allow overwriting of the db name in the tracking table.
=> Allow override of db name

druzhba/db.py, druzhba/main.py, test/unit/test_db.py
Add a config param to allow overwriting of the db name in the tracking table across the database
=> Create the ability to override the database name across the database
